// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (line1, line2, city, state_name, postal_code, country, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, line1, line2, city, state_name, postal_code, country, created_at, updated_at, user_id, is_primary
`

type CreateAddressParams struct {
	Line1      string
	Line2      pgtype.Text
	City       string
	StateName  string
	PostalCode string
	Country    string
	UserID     int32
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.StateName,
		arg.PostalCode,
		arg.Country,
		arg.UserID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.StateName,
		&i.PostalCode,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.IsPrimary,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT line1, line2, city, state_name, postal_code, country FROM addresses
WHERE user_id = $1
`

type GetUserAddressesRow struct {
	Line1      string
	Line2      pgtype.Text
	City       string
	StateName  string
	PostalCode string
	Country    string
}

func (q *Queries) GetUserAddresses(ctx context.Context, userID int32) ([]GetUserAddressesRow, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAddressesRow
	for rows.Next() {
		var i GetUserAddressesRow
		if err := rows.Scan(
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.StateName,
			&i.PostalCode,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
