// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (category_name, image_url, parent_id)
VALUES ($1, $2, $3)
RETURNING id, category_name, image_url, created_at, updated_at, parent_id
`

type CreateCategoryParams struct {
	CategoryName string
	ImageUrl     pgtype.Text
	ParentID     pgtype.Int4
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.CategoryName, arg.ImageUrl, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT category_name, image_url
FROM categories
WHERE category_name = $1
`

type GetCategoryByNameRow struct {
	CategoryName string
	ImageUrl     pgtype.Text
}

func (q *Queries) GetCategoryByName(ctx context.Context, categoryName string) (GetCategoryByNameRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, categoryName)
	var i GetCategoryByNameRow
	err := row.Scan(&i.CategoryName, &i.ImageUrl)
	return i, err
}

const getParentCategories = `-- name: GetParentCategories :many
SELECT category_name, image_url
FROM categories
WHERE parent_id IS NULL
`

type GetParentCategoriesRow struct {
	CategoryName string
	ImageUrl     pgtype.Text
}

func (q *Queries) GetParentCategories(ctx context.Context) ([]GetParentCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getParentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParentCategoriesRow
	for rows.Next() {
		var i GetParentCategoriesRow
		if err := rows.Scan(&i.CategoryName, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCategories = `-- name: GetSubCategories :many
SELECT category_name, image_url
FROM categories
WHERE parent_id = $1
`

type GetSubCategoriesRow struct {
	CategoryName string
	ImageUrl     pgtype.Text
}

func (q *Queries) GetSubCategories(ctx context.Context, parentID pgtype.Int4) ([]GetSubCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getSubCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubCategoriesRow
	for rows.Next() {
		var i GetSubCategoriesRow
		if err := rows.Scan(&i.CategoryName, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
