// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         int32
	Line1      string
	Line2      pgtype.Text
	City       string
	StateName  string
	PostalCode string
	Country    string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UserID     int32
	IsPrimary  bool
}

type User struct {
	ID             int32
	FullName       string
	Email          string
	HashedPassword string
	ImageUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
