// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (product_name, product_description, brand, price, mode, attributes, category_id, subcategory_id, user_id, images)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, product_name, product_description, brand, price, mode, attributes, category_id, subcategory_id, user_id, created_at, updated_at, images, is_deleted
`

type CreateProductParams struct {
	ProductName        string
	ProductDescription string
	Brand              string
	Price              pgtype.Numeric
	Mode               SellMode
	Attributes         []byte
	CategoryID         int32
	SubcategoryID      int32
	UserID             int32
	Images             []string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductName,
		arg.ProductDescription,
		arg.Brand,
		arg.Price,
		arg.Mode,
		arg.Attributes,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.UserID,
		arg.Images,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.ProductDescription,
		&i.Brand,
		&i.Price,
		&i.Mode,
		&i.Attributes,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Images,
		&i.IsDeleted,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, product_name, product_description, brand, price, mode, attributes, category_id, subcategory_id, user_id, created_at, updated_at, images, is_deleted FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.ProductDescription,
		&i.Brand,
		&i.Price,
		&i.Mode,
		&i.Attributes,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Images,
		&i.IsDeleted,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT id, product_name, product_description, brand, price, mode, attributes, category_id, subcategory_id, user_id, created_at, updated_at, images, is_deleted FROM products
WHERE category_id = $1
`

func (q *Queries) GetProductsByCategory(ctx context.Context, categoryID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.ProductDescription,
			&i.Brand,
			&i.Price,
			&i.Mode,
			&i.Attributes,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Images,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
